### ISSUE TITLE
SOON!

### ISSUE THREAD

**Issue by ItsToxicGG** [ItsToxicGG/MurderMysteryy#2]
- setup commands
- arena working
- much more !

**Comment by Tuvqlu** [comment]
You got this! I’m really excited to see this plugin because Palermo Town doesn’t work and I already built the mm map lol! A suggestion: add a scoreboard, and a hub where you wait for enough players! Maybe even a cosmetic menu! I’m so excited toxic

**Comment by ItsToxicGG** [comment]
and all the others

**Comment by Tuvqlu** [comment]
If you can though you should add the hub like while you wait for players cuz yep lol

**Comment by ItsToxicGG** [comment]
> I’m so excited! Here are my ideas for cosmetics! Basically, there are levels you gain xp from winning games and stuff
> 
> 100 Coins a level 5 Coins A kill 10 Coins a innocent win 15 coins a hero win 20 coins a murder win
> 
> 100XP A murder Win 10xp a kill 50XP an innocent win 75XP hero win
> 
> §1Murder Sword:
> 
> Default: §6Wooden
> 
> (8) §8Stone (15) §7Iron (22) §bDiamond (28) §4Netherite
> 
> §3Kill Sound:
> 
> Default: None
> 
> (5) §dOink (10) §3Explosion (16) §eBell (19) §6Note (24) §7Raid (29) §aLevel Up
> 
> §4Death Phrase:
> 
> Default: §7killed (§cTuvqlu§r was killed by §4The Murderer)
> 
> (3) §6Found (§cTuvqlu§r was found and savagely killed by §4The Murderer) (8) §8Just in time (§4The Murderer killed §cTuvqlu§r just before they revealed who it was. Just in time…) (13) §4Savage (§cTuvqlu§r was savagely beaten and killed by §4The Murderer) (21) §dHiding (§4The Murderer§r found §cTuvqlu’s§r hiding place and eternally shrouded them (27) §aGood §rand §cEvil (§4The Murderer’s§r cold heart shredded §cTuvqlu’s§r good heart. :()
> 
> §5Shooting The Murderer Phrases
> 
> Default: §7Shot (§aTuvqlu§r shot §4The Murderer. §eThe innocents have won! §bGG!)
> 
> (4) §8Sniped (§aTuvqlu§r sniped §4The Murderer. §eThe innocents have won! §bGG!) (9) §4Targeted (§aTuvqlu§r precisely targeted and took down §4The Murderer. §eThe innocents have won! §bGG!) (12) §3Wiped Out (§aTuvqlu§r wiped out §4The Murderer. §eThe innocents have won! §bGG! (18) §eBlast (§aTuvqlu§r blasted §4The Murderer. §eThe innocents have won! §bGG! (22) §4Piercing (§aTuvqlu’s§r arrow pierced §4The Murderer. §eThe innocents have won! §bGG! (26) §cStealthy Explosion (Stealthy §aTuvqlu§r precisely exploded §4The Murderer. §eThe innocents have won! §bGG! (30) §6Detective Track Down (Detective §aTuvqlu§r tracked down and erased §4The Murderer§r from the earth. §eThe innocents have won! §bGG!

i dont really understand about the netherrite sword its not in pocketmine../

**Comment by ItsToxicGG** [comment]
but all these features may be added in a month or a long time because its alot some features i may not make..

**Comment by Tuvqlu** [comment]
Of course lol that’s a lot of cosmetics!
